FROM node:22-alpine
WORKDIR /app

# Instala pnpm globalmente
RUN npm install -g pnpm

# Copia solo package.json para instalar dependencias
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Montaremos el resto con volumen, así que no copiamos todo
EXPOSE 5173
CMD ["pnpm", "dev"]